webapp/lector/models.py
from webapp.db import db


class Lecturer(db.Model): # отсюда  https://pythobyte.com/using-sqlalchemy-with-flask-and-postgresql-056e4a45/
    lecturer_id = db.Column(db.Integer, primary_key=True) # id лектора
    name = db.Column(db.String(80), nullable=False) # Имя
    lastname = db.Column(db.String(80), nullable=False) # Фамилия
    middlename = db.Column(db.String(80), nullable=False) # Отчество
    birthday = db.Column(db.DateTime, nullable=True) # Дата рождения
    tel = db.Column(db.Text, nullable=False) # телефон
    email = db.Column(db.String, nullable=False) # электронная почта
    city = db.Column(db.String(80), nullable=False) # город проживания
    passport_number = db.Column(db.Integer, nullable=True) # Серия и номер паспорта
    passport_who = db.Column(db.Text, nullable=False) # когда и кем выдан
    issued = db.Column(db.DateTime, nullable=True) # Дата выдачи
    adress = db.Column(db.String, nullable=False) # Адрес проживания
    work = db.Column(db.String, nullable=False) # Место работы и адрес
    agreement_number = db.Column(db.String(80), nullable=False) # Номер договора
    created_at = db.Column(db.DateTime, nullable=True) # Дата создания договора
    # status = db.Column(db.Boolean, nullable=True, default=True) # Статус лектора
    rang = db.Column(db.String(32), nullable=False) # ранг КОЛа


    # def __repr__(self):
    #     return f'Lecturer : {self.surname} {self.lastname} {self.middlename}, {self.email}, {self.tel}, {self.work}'

webapp/lector/forms.py
# from typing import DefaultDict
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, IntegerField, DateField, SubmitField
from wtforms.validators import DataRequired, Email

class AddForm(FlaskForm):
    name = StringField ('Имя', [DataRequired()])
    lastname = StringField ('Фамилия', [DataRequired()])
    middlename = StringField ('Отчество', [DataRequired()])
    birthday = DateField ('Дата рождения', [DataRequired()])
    tel = StringField ('Телефон', [DataRequired()])
    email = StringField ('E-mail', [DataRequired(), Email()])
    city = StringField ('Город', [DataRequired()])
    passport_number = IntegerField ('Серия и номер паспорта', [DataRequired()])
    passport_who = StringField ('Кем выдан паспорт', [DataRequired()])
    issued = DateField ('Дата выдачи паспорта', [DataRequired()])
    adress = StringField ('Адрес проживания', [DataRequired()])
    agreement_number = StringField ('Номер договора', [DataRequired()])
    work = StringField ('Место и адрес работы', [DataRequired()])
    created_at = DateField ('Дата создания договора', [DataRequired()])
    # status = BooleanField ('Активность лектора', [DataRequired()])
    rang = StringField ('Ранг лектора', [DataRequired()])
    submit = SubmitField ('Добавить лектора')
# new_lecturer = Lecturer(surname=surname, lastname=lastname, 
# middlename=middlename, birthday=birthday, tel=tel, email=email, 
# city=city, passport_number=passport_number, passport_who=passport_who, 
# issued=issued, adress=adress, agreement_number=agreement_number, work=work,
# created_at=created_at, rang=rang ) # создаем объект в памяти соответствующий БД

webapp/lector/views.py
#  from webapp.db import db
from webapp.lector.forms import AddForm
from flask import Blueprint, redirect, render_template, flash
from webapp.db import db
from webapp.lector.models import Lecturer

blueprint = Blueprint('lector', __name__)

@blueprint.route("/", methods=['POST', 'GET']) # add
def home():
    # return 'Hello123545'
    all_lectors = Lecturer.query.all()
    return render_template("index.html", all_lectors=all_lectors)  # add


@blueprint.route('/add-lector')
def add_lector():
     form = AddForm()
     return render_template('add-lector.html', form=form)

@blueprint.route('/add-lector-process', methods=['POST'])
def add_lector_process(): 
    form = AddForm()
    new_lecturer = Lecturer(name=form.name.data, 
                            lastname=form.lastname.data,
                            middlename=form.middlename.data,
                            birthday=form.birthday.data,
                            tel=form.tel.data,
                            email=form.email.data,
                            city=form.city.data,
                            passport_number=form.passport_number.data,
                            passport_who=form.passport_who.data,
                            issued=form.issued.data,
                            adress=form.adress.data,
                            agreement_number=form.agreement_number.data,
                            work=form.work.data,
                            created_at=form.created_at.data,
                            rang=form.rang.data)
    db.session.add(new_lecturer)
    db.session.commit()
    flash ('Лектор добавлен') 
    return render_template('index.html', form=form)

    

# @blueprint.route('/all-lectors')
# def all_lectors():
#     all_lectors = Lecturer.query.order_by(Lecturer.surname).all()
#     return render_template("all-lectors.html", all_lectors=all_lectors, title="Список всех лекторов")

# @blueprint.route('/all-lectors/<int:lecturer_id>') # Cтраничка лектора
# def lector_detail(lecturer_id):
#     lector = Lecturer.query.get(lecturer_id)
#     return render_template("lector.html", title="Страница лектора", lector=lector)
    

# @blueprint.route('/all-lectors/<int:lecturer_id>/delete') #Удаление лектора из базы
# def lector_delete(lecturer_id):
#     lector = Lecturer.query.get_or_404(lecturer_id)
#     try:
#         # db.session.delete(lector)
#         # db.session.commit()
#         return redirect('/')
#     except:
#         return "При удалении произошла ошибка"

# @blueprint.route('/all-lectors/<int:lecturer_id>/update', methods=['POST','GET'])
# def lector_update(lecturer_id):
#     if request.method == "POST":
#         lecturer = Lecturer.query.get(lecturer_id) 
#         lecturer.surname = request.form['surname']
#         lecturer.lastname = request.form['lastname']
#         lecturer.middlename = request.form['middlename']
#         lecturer.birthday = request.form['birthday']
#         lecturer.tel = request.form['tel']
#         lecturer.email = request.form['email']
#         lecturer.city = request.form['city']
#         lecturer.passport_number = request.form['passport_number']
#         lecturer.passport_who = request.form['passport_who']
#         lecturer.issued = request.form['issued']
#         lecturer.adress = request.form['adress']
#         lecturer.agreement_number = request.form['agreement_number']
#         lecturer.work = request.form['work']
#         lecturer.created_at = request.form['created_at']
#    #     lecturer.status = request.form['status']
#         lecturer.rang = request.form['rang']        
#         # db.session.commit() # подтверждение изменений
#         return redirect(f'/all-lectors/{lecturer_id}/success-lector') # проброс на страницу лектора
        
#     else:
#         new_lecturer = Lecturer.query.get(lecturer_id)
#         # считывает из таблицы лекторов все строчки и сортировка по дате добавления
#     return render_template("lector-update.html", lector=new_lecturer, title="Редактирование информации о лекторе")

webapp/templates/add-lector.html
{% extends 'base.html'%}


{% block title %} {{ title }} {% endblock %}

{% block body %}   

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-warning" role='alert'>
    {%for message in messages%}
        {{message}} <br>
    {%endfor%}
</div>
{% endif %}
{% endwith %}

<div class="page-content">
    <div class="container-fluid">
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="row">
                        <div class="col">
                            <h4 class="page-title">Добавление нового лектора</h4>
                            
                        </div><!--end col-->
                        <div class="col-auto align-self-center">
                            <a href="#" class="btn btn-sm btn-outline-primary" id="Dash_Date">
                                <span class="day-name" id="Day_Name">Today:</span>&nbsp;
                                <span class="" id="Select_date">Jan 11</span>
                                <i data-feather="calendar" class="align-self-center icon-xs ml-1"></i>
                            </a>
                            <a href="#" class="btn btn-sm btn-outline-primary">
                                <i data-feather="download" class="align-self-center icon-xs"></i>
                            </a>
                        </div><!--end col-->  
                    </div><!--end row-->                                                              
                </div><!--end page-title-box-->
            </div><!--end col-->
        </div><!--end row-->
        <!-- end page title end breadcrumb -->
        <form action="{{ url_for('lector.add_lector_process') }}" method="post" enctype="multipart/form-data">
            {{ form.hidden_tag() }}

                        <div class="row">
                        <div class="col-lg-6">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Внесите данные лектора</h4>
                                    <p class="text-muted mb-0">Внесите данные для добавления лектора в базу</p>
                                </div><!--end card-header-->
                                <div class="card-body">
                                    <form class="">
                                        <div class="row">
                                            
                                            
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="username">{{form.lastname.label}}</label>
                                                    {{ form.lastname (class="form-control")}}
                                                </div>
                                            </div>

                                            


                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="username">{{form.name.label}}</label>
                                                    {{ form.name(class="form-control") }}
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="username">{{form.middlename.label}}</label>
                                                    {{ form.middlename(class="form-control") }}
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="subject">{{form.tel.label}}</label>
                                                    {{ form.tel(class="form-control") }}
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="useremail">{{form.email.label}}</label>
                                                    {{ form.email(class="form-control") }}
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="subject">{{form.city.label}}</label>
                                                    {{ form.city(class="form-control") }} 
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="username">{{form.passport_number.label}}</label>
                                                    {{ form.passport_number(class="form-control") }} 
                                                </div>
                                            </div>


                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="username">{{form.issued.label}}</label>
                                                    {{ form.issued(class="form-control") }}
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="username">{{form.passport_who.label}}</label>
                                                    {{ form.passport_who(class="form-control") }}
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="username">{{form.adress.label}}</label>
                                                    {{ form.adress(class="form-control") }}
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="username">{{form.birthday.label}}</label>
                                                    {{ form.birthday(class="form-control") }}
                                                </div>
                                            </div>

                                            



                                        </div>
                                        
                                    
                                </div><!--end card-body-->
                            </div><!--end card-->

                            </div> <!-- end col -->

                            <div class="col-lg-6">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">Данные договора</h4>
                                    <p class="text-muted mb-0">Внимательно внесите данные в базу</p>
                                </div><!--end card-header-->
                                <div class="card-body">
                                    
                                        <div class="row">
                                            
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="subject">{{form.agreement_number.label}}</label>
                                                    {{form.agreement_number(class="form-control")}}
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="useremail">{{form.created_at.label}}</label>
                                                    {{form.created_at(class="form-control")}}
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="subject">{{form.work.label}}</label>
                                                    {{form.work(class="form-control")}}
                                                </div>
                                            </div>

                                            <div class="col-sm-4">
                                                <select>
                                                    {{form.rang(class="form-control")}}
                                                    <option>{{form.rang.label}}</option>
                                                    <option>Локальный</option>
                                                    <option>Региональный</option>
                                                    <option>Национальный</option>
                                                </select>
                                            </div>

                                            <!-- <div class="col-md-8">
                                                <div class="form-group">
                                                    <label>Файл договора</label> 
                                                    <div class="custom-file">
                                                      <input type="file" class="custom-file-input" name="image" id="image">
                                                      <label class="custom-file-label" for="image">Выберите файл договора...</label>
                                                    </div>
                                                  </div>
                                                </div> -->

                                        </div>

                                        <!-- <div class="form-group row">

                                            <div class="col-lg-4">
                                                <div class="custom-control custom-switch switch-primary">
                                                    <input type="checkbox" name='status'class="custom-control-input" id="status" checked>
                                                    <label class="custom-control-label" for="customSwitchPrimary">Активный</label>
                                                </div>
                                            </div> -->
                                            
                                            
                                        <!-- </div>--> 

                                        

                                    
                                </div><!--end card-body-->
                            </div>
                            
                            <button type="submit" class="btn btn-primary btn-xl">{{ form.submit }}</button>
                        </form>
                                    </div>

    </div><!-- container -->
{% endblock %}
            <!-- end page content -->
        </div>
        <!-- end page-wrapper -->

</html>

webapp/templates/all-lectors.html
{% extends 'base.html'%}


{% block title %} {{ title }} {% endblock %}

{% block body %}   
<div class="page-content">
    <div class="container-fluid">
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="row">
                        <div class="col">
                            <h4 class="page-title">Список всех лекторов</h4>
                            
                        </div><!--end col-->
                        <div class="col-auto align-self-center">
                            <a href="#" class="btn btn-sm btn-outline-primary" id="Dash_Date">
                                <span class="day-name" id="Day_Name">Today:</span>&nbsp;
                                <span class="" id="Select_date">Jan 11</span>
                                <i data-feather="calendar" class="align-self-center icon-xs ml-1"></i>
                            </a>
                            <a href="#" class="btn btn-sm btn-outline-primary">
                                <i data-feather="download" class="align-self-center icon-xs"></i>
                            </a>
                        </div><!--end col-->  
                    </div><!--end row-->                                                              
                </div><!--end page-title-box-->
            </div><!--end col-->
        </div><!--end row-->
        <!-- end page title end breadcrumb -->



        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Buttons example</h4>
                <div class="row">
                    <div class="col-sm-12 col-md-6">
                        <div class="dt-buttons btn-group flex-wrap"> 
                            <button class="btn btn-secondary buttons-copy buttons-html5" tabindex="0" aria-controls="datatable-buttons" type="button"><span>Copy</span></button> 
                            <button class="btn btn-secondary buttons-excel buttons-html5" tabindex="0" aria-controls="datatable-buttons" type="button"><span>Excel</span></button>
                            <button class="btn btn-secondary buttons-pdf buttons-html5" tabindex="0" aria-controls="datatable-buttons" type="button"><span>PDF</span></button> 
                            
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        <div id="datatable-buttons_filter" class="dataTables_filter">
                            <label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="datatable-buttons"></label>
                        </div>
                    </div>
                </div>

                        
                    </div><!--end card-header-->


                    
                    <div class="card-body">  
                        <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                            <thead>
                                <tr>
                                    <th>ФИО</th>
                                    <th>Дата рождения</th>
                                    <th>Телефон</th>
                                    <th>Email</th>
                                    <th>Город</th>
                                    <th>Место работы</th>
                                    <th>Ранг</th>
                                    <th>Действия</th>
                                </tr>
                                </thead>


                            <tbody>
                           
                                                        

                            {% for lector in all_lectors %}
                            <tr>
                                <td><a href="/all-lectors/{{ lector.lecturer_id }}">{{lector.surname}}  {{lector.lastname}}  {{lector.middlename}} </a> </td>
                                <td>{{lector.birthday}}</td>
                                <td>{{lector.tel}}></td>
                                <td>{{lector.email}}</td>
                                <td>{{lector.city}}</td>
                                <td>{{lector.work}}</td>
                                <td>{{lector.rang}}</td>
                                <td>                                                       
                                    <a href="/all-lectors/{{ lector.lecturer_id }}" class="mr-2"><i class="las la-pen text-info font-18"></i></a>
                                    <a href="#"><i class="las la-trash-alt text-danger font-18"></i></a>
                                </td>
                            </tr>
                            {% endfor %} 
                            
                            </tbody>
                        </table>    
                        
                        <div class="row">
                            <div class="col-sm-12 col-md-5">
                                <div class="dataTables_info" id="datatable-buttons_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
                            </div>
                            <div class="col-sm-12 col-md-7">
                                <div class="dataTables_paginate paging_simple_numbers" id="datatable-buttons_paginate">
                                    <ul class="pagination">
                                        <li class="paginate_button page-item previous disabled" id="datatable-buttons_previous">
                                            <a href="#" aria-controls="datatable-buttons" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
                                        </li>

                                        <li class="paginate_button page-item active">
                                            <a href="#" aria-controls="datatable-buttons" data-dt-idx="1" tabindex="0" class="page-link">1</a>
                                        </li>

                                        <li class="paginate_button page-item ">
                                            <a href="#" aria-controls="datatable-buttons" data-dt-idx="2" tabindex="0" class="page-link">2</a>
                                        </li>

                                        <li class="paginate_button page-item ">
                                            <a href="#" aria-controls="datatable-buttons" data-dt-idx="3" tabindex="0" class="page-link">3</a>
                                        </li>
                                        
                                        <li class="paginate_button page-item ">
                                            <a href="#" aria-controls="datatable-buttons" data-dt-idx="4" tabindex="0" class="page-link">4</a>
                                        </li>
                                        
                                        <li class="paginate_button page-item ">
                                            <a href="#" aria-controls="datatable-buttons" data-dt-idx="5" tabindex="0" class="page-link">5</a>
                                        </li>
                                        
                                        <li class="paginate_button page-item ">
                                            <a href="#" aria-controls="datatable-buttons" data-dt-idx="6" tabindex="0" class="page-link">6</a>
                                        </li>
                                        
                                        <li class="paginate_button page-item next" id="datatable-buttons_next">
                                            <a href="#" aria-controls="datatable-buttons" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>


                    
                </div>
            </div> <!-- end col -->
        </div> <!-- end row -->
             
        
        

    </div><!-- container -->
   {% endblock %}
            <!-- end page content -->
        </div>
        <!-- end page-wrapper -->
   
        
        
  

</html>

webapp/templates/home.html
<!-- {% extends "base.html" %}
{% block content %}
<div class="bg-white rounded shadow p-6 m-4 w-full lg:w-3/4 lg:max-w-lg">
  <div class="mb-4">
    <h1 class="text-grey-darkest">Список лекторов</h1>
    <div class="flex mt-4">
      {% include "partials/_form.html" %}
    </div>
  </div>

  <form action="/update/{{ lecturer.id }}" method="post" class="inline-flex">
    <input class="shadow appearance-none border rounded w-full py-2 px-3 mr-4 text-grey-darker"
      placeholder="Add Todo" type="text" name="name" value="{{ lecturer.surname }}"/>

    
    
      <button
      class="flex-no-shrink p-2 border-2 rounded text-teal border-teal hover:text-white hover:bg-teal bg-green-600"
      type="submit"
    >
      Update
    </button>
  </form>
  <!--<div>
    {% if tasks %}
    {% for task in tasks %}
    <div class="flex mb-4 items-center">
      <p class="w-full text-grey-darkest">
        <a href="#">{{ task.name }}</a>
      </p>
      <a class="flex-no-shrink p-2 ml-2 border-2 rounded text-red border-red hover:text-white hover:bg-red bg-red-600"
      href="/delete/{{ task.id }}"
    >
      Remove
    </a>
    </div>
    {% endfor %}
    {% else %}

    <p class="text-center">Нет Лекторов в всписке</p>

    {% endif %}
  </div>-->
</div>
{% endblock content %} -->

webapp/templates/update.html
{% extends 'base.html' %}
{% block content %}
<div class="mb-4">
  <h1 class="text-grey-darkest">{{ title }}</h1>
  <div class="flex mt-4">
    <form action="/update/{{ task.id }}" method="post" class="inline-flex">
      <input
        class="shadow appearance-none border rounded w-full py-2 px-3 mr-4 text-grey-darker"
        placeholder="Add Todo"
        type="text"
        name="name"
        value="{{ task.name }}"
      />
      <button
        class="flex-no-shrink p-2 border-2 rounded text-teal border-teal hover:text-white hover:bg-teal bg-green-600"
        type="submit"
      >
        Update
      </button>
    </form>
  </div>
</div>

{% endblock content %}